// <auto-generated />
using System;
using Klinika.DATA;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Klinika.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260128153121_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Klinika.Models.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdditionalInfo")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ApartmentNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("StreetName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StreetNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Addresses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityId = 1,
                            StreetName = "Admin Street",
                            StreetNumber = "1"
                        });
                });

            modelBuilder.Entity("Klinika.Models.AppointmentSlot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId", "Date", "StartTime")
                        .IsUnique();

                    b.ToTable("AppointmentSlots");
                });

            modelBuilder.Entity("Klinika.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Name", "Country")
                        .IsUnique();

                    b.ToTable("Cities", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Country = "Serbia",
                            Name = "Beograd",
                            PostalCode = "11000"
                        },
                        new
                        {
                            Id = 2,
                            Country = "Serbia",
                            Name = "Novi Sad",
                            PostalCode = "21000"
                        },
                        new
                        {
                            Id = 3,
                            Country = "Serbia",
                            Name = "Niš",
                            PostalCode = "18000"
                        },
                        new
                        {
                            Id = 4,
                            Country = "Serbia",
                            Name = "Kragujevac",
                            PostalCode = "34000"
                        },
                        new
                        {
                            Id = 5,
                            Country = "Serbia",
                            Name = "Subotica",
                            PostalCode = "24000"
                        },
                        new
                        {
                            Id = 6,
                            Country = "Serbia",
                            Name = "Zrenjanin",
                            PostalCode = "23000"
                        },
                        new
                        {
                            Id = 7,
                            Country = "Serbia",
                            Name = "Pančevo",
                            PostalCode = "26000"
                        },
                        new
                        {
                            Id = 8,
                            Country = "Serbia",
                            Name = "Čačak",
                            PostalCode = "32000"
                        },
                        new
                        {
                            Id = 9,
                            Country = "Serbia",
                            Name = "Kruševac",
                            PostalCode = "37000"
                        },
                        new
                        {
                            Id = 10,
                            Country = "Serbia",
                            Name = "Kraljevo",
                            PostalCode = "36000"
                        },
                        new
                        {
                            Id = 11,
                            Country = "Serbia",
                            Name = "Smederevo",
                            PostalCode = "11300"
                        },
                        new
                        {
                            Id = 12,
                            Country = "Serbia",
                            Name = "Leskovac",
                            PostalCode = "16000"
                        },
                        new
                        {
                            Id = 13,
                            Country = "Serbia",
                            Name = "Užice",
                            PostalCode = "31000"
                        },
                        new
                        {
                            Id = 14,
                            Country = "Serbia",
                            Name = "Vranje",
                            PostalCode = "17500"
                        },
                        new
                        {
                            Id = 15,
                            Country = "Serbia",
                            Name = "Šabac",
                            PostalCode = "15000"
                        },
                        new
                        {
                            Id = 16,
                            Country = "Serbia",
                            Name = "Valjevo",
                            PostalCode = "14000"
                        },
                        new
                        {
                            Id = 17,
                            Country = "Serbia",
                            Name = "Sombor",
                            PostalCode = "25000"
                        },
                        new
                        {
                            Id = 18,
                            Country = "Serbia",
                            Name = "Požarevac",
                            PostalCode = "12000"
                        },
                        new
                        {
                            Id = 19,
                            Country = "Serbia",
                            Name = "Pirot",
                            PostalCode = "18300"
                        },
                        new
                        {
                            Id = 20,
                            Country = "Serbia",
                            Name = "Zaječar",
                            PostalCode = "19000"
                        },
                        new
                        {
                            Id = 21,
                            Country = "Serbia",
                            Name = "Kikinda",
                            PostalCode = "23300"
                        },
                        new
                        {
                            Id = 22,
                            Country = "Serbia",
                            Name = "Sremska Mitrovica",
                            PostalCode = "22000"
                        },
                        new
                        {
                            Id = 23,
                            Country = "Serbia",
                            Name = "Jagodina",
                            PostalCode = "35000"
                        },
                        new
                        {
                            Id = 24,
                            Country = "Serbia",
                            Name = "Vršac",
                            PostalCode = "26300"
                        },
                        new
                        {
                            Id = 25,
                            Country = "Serbia",
                            Name = "Bor",
                            PostalCode = "19210"
                        },
                        new
                        {
                            Id = 26,
                            Country = "Serbia",
                            Name = "Prokuplje",
                            PostalCode = "18400"
                        },
                        new
                        {
                            Id = 27,
                            Country = "Serbia",
                            Name = "Loznica",
                            PostalCode = "15300"
                        },
                        new
                        {
                            Id = 28,
                            Country = "Serbia",
                            Name = "Bečej",
                            PostalCode = "21220"
                        },
                        new
                        {
                            Id = 29,
                            Country = "Serbia",
                            Name = "Aranđelovac",
                            PostalCode = "34300"
                        },
                        new
                        {
                            Id = 30,
                            Country = "Serbia",
                            Name = "Novi Pazar",
                            PostalCode = "36300"
                        },
                        new
                        {
                            Id = 31,
                            Country = "Serbia",
                            Name = "Negotin",
                            PostalCode = "19300"
                        },
                        new
                        {
                            Id = 32,
                            Country = "Serbia",
                            Name = "Paraćin",
                            PostalCode = "35250"
                        },
                        new
                        {
                            Id = 33,
                            Country = "Serbia",
                            Name = "Inđija",
                            PostalCode = "22320"
                        },
                        new
                        {
                            Id = 34,
                            Country = "Serbia",
                            Name = "Lazarevac",
                            PostalCode = "11550"
                        },
                        new
                        {
                            Id = 35,
                            Country = "Serbia",
                            Name = "Ćuprija",
                            PostalCode = "35230"
                        },
                        new
                        {
                            Id = 36,
                            Country = "Serbia",
                            Name = "Mladenovac",
                            PostalCode = "11400"
                        },
                        new
                        {
                            Id = 37,
                            Country = "Serbia",
                            Name = "Ruma",
                            PostalCode = "22400"
                        },
                        new
                        {
                            Id = 38,
                            Country = "Serbia",
                            Name = "Stara Pazova",
                            PostalCode = "22300"
                        },
                        new
                        {
                            Id = 39,
                            Country = "Serbia",
                            Name = "Kovačica",
                            PostalCode = "26210"
                        },
                        new
                        {
                            Id = 40,
                            Country = "Serbia",
                            Name = "Kula",
                            PostalCode = "25230"
                        },
                        new
                        {
                            Id = 41,
                            Country = "Serbia",
                            Name = "Gornji Milanovac",
                            PostalCode = "32300"
                        },
                        new
                        {
                            Id = 42,
                            Country = "Serbia",
                            Name = "Temerin",
                            PostalCode = "21235"
                        },
                        new
                        {
                            Id = 43,
                            Country = "Serbia",
                            Name = "Čoka",
                            PostalCode = "23320"
                        },
                        new
                        {
                            Id = 44,
                            Country = "Serbia",
                            Name = "Aleksinac",
                            PostalCode = "18220"
                        },
                        new
                        {
                            Id = 45,
                            Country = "Serbia",
                            Name = "Novi Bečej",
                            PostalCode = "23272"
                        },
                        new
                        {
                            Id = 46,
                            Country = "Serbia",
                            Name = "Bačka Palanka",
                            PostalCode = "21400"
                        },
                        new
                        {
                            Id = 47,
                            Country = "Serbia",
                            Name = "Svilajnac",
                            PostalCode = "35210"
                        },
                        new
                        {
                            Id = 48,
                            Country = "Serbia",
                            Name = "Petrovac na Mlavi",
                            PostalCode = "12300"
                        },
                        new
                        {
                            Id = 49,
                            Country = "Serbia",
                            Name = "Ada",
                            PostalCode = "24430"
                        },
                        new
                        {
                            Id = 50,
                            Country = "Serbia",
                            Name = "Šid",
                            PostalCode = "22240"
                        },
                        new
                        {
                            Id = 51,
                            Country = "Serbia",
                            Name = "Priboj",
                            PostalCode = "31330"
                        },
                        new
                        {
                            Id = 52,
                            Country = "Serbia",
                            Name = "Srbobran",
                            PostalCode = "21480"
                        },
                        new
                        {
                            Id = 53,
                            Country = "Serbia",
                            Name = "Vlasotince",
                            PostalCode = "16210"
                        },
                        new
                        {
                            Id = 54,
                            Country = "Serbia",
                            Name = "Kučevo",
                            PostalCode = "12240"
                        },
                        new
                        {
                            Id = 55,
                            Country = "Serbia",
                            Name = "Velika Plana",
                            PostalCode = "11320"
                        },
                        new
                        {
                            Id = 56,
                            Country = "Serbia",
                            Name = "Knjaževac",
                            PostalCode = "19350"
                        },
                        new
                        {
                            Id = 57,
                            Country = "Serbia",
                            Name = "Apatin",
                            PostalCode = "25260"
                        },
                        new
                        {
                            Id = 58,
                            Country = "Serbia",
                            Name = "Arilje",
                            PostalCode = "31230"
                        },
                        new
                        {
                            Id = 59,
                            Country = "Serbia",
                            Name = "Žabalj",
                            PostalCode = "21230"
                        },
                        new
                        {
                            Id = 60,
                            Country = "Serbia",
                            Name = "Nova Varoš",
                            PostalCode = "31320"
                        },
                        new
                        {
                            Id = 61,
                            Country = "Serbia",
                            Name = "Senta",
                            PostalCode = "24400"
                        },
                        new
                        {
                            Id = 62,
                            Country = "Serbia",
                            Name = "Kovin",
                            PostalCode = "26220"
                        },
                        new
                        {
                            Id = 63,
                            Country = "Serbia",
                            Name = "Surdulica",
                            PostalCode = "17530"
                        },
                        new
                        {
                            Id = 64,
                            Country = "Serbia",
                            Name = "Žagubica",
                            PostalCode = "12330"
                        },
                        new
                        {
                            Id = 65,
                            Country = "Serbia",
                            Name = "Kladovo",
                            PostalCode = "19320"
                        },
                        new
                        {
                            Id = 66,
                            Country = "Serbia",
                            Name = "Despotovac",
                            PostalCode = "35213"
                        },
                        new
                        {
                            Id = 67,
                            Country = "Serbia",
                            Name = "Beočin",
                            PostalCode = "21300"
                        },
                        new
                        {
                            Id = 68,
                            Country = "Serbia",
                            Name = "Bački Petrovac",
                            PostalCode = "21470"
                        },
                        new
                        {
                            Id = 69,
                            Country = "Serbia",
                            Name = "Rekovac",
                            PostalCode = "35243"
                        },
                        new
                        {
                            Id = 70,
                            Country = "Serbia",
                            Name = "Titel",
                            PostalCode = "21240"
                        },
                        new
                        {
                            Id = 71,
                            Country = "Serbia",
                            Name = "Golubac",
                            PostalCode = "12223"
                        },
                        new
                        {
                            Id = 72,
                            Country = "Serbia",
                            Name = "Barajevo",
                            PostalCode = "11460"
                        },
                        new
                        {
                            Id = 73,
                            Country = "Serbia",
                            Name = "Babušnica",
                            PostalCode = "18330"
                        },
                        new
                        {
                            Id = 74,
                            Country = "Serbia",
                            Name = "Dimitrovgrad",
                            PostalCode = "18320"
                        },
                        new
                        {
                            Id = 75,
                            Country = "Serbia",
                            Name = "Bela Palanka",
                            PostalCode = "18310"
                        },
                        new
                        {
                            Id = 76,
                            Country = "Serbia",
                            Name = "Boljevac",
                            PostalCode = "19370"
                        },
                        new
                        {
                            Id = 77,
                            Country = "Serbia",
                            Name = "Majdanpek",
                            PostalCode = "19250"
                        },
                        new
                        {
                            Id = 78,
                            Country = "Serbia",
                            Name = "Novi Kneževac",
                            PostalCode = "23330"
                        },
                        new
                        {
                            Id = 79,
                            Country = "Serbia",
                            Name = "Sopot",
                            PostalCode = "11450"
                        },
                        new
                        {
                            Id = 80,
                            Country = "Serbia",
                            Name = "Veliko Gradište",
                            PostalCode = "12220"
                        },
                        new
                        {
                            Id = 81,
                            Country = "Serbia",
                            Name = "Žitište",
                            PostalCode = "23210"
                        },
                        new
                        {
                            Id = 82,
                            Country = "Serbia",
                            Name = "Ub",
                            PostalCode = "14210"
                        },
                        new
                        {
                            Id = 83,
                            Country = "Serbia",
                            Name = "Bajina Bašta",
                            PostalCode = "31250"
                        },
                        new
                        {
                            Id = 84,
                            Country = "Serbia",
                            Name = "Kosjerić",
                            PostalCode = "31260"
                        },
                        new
                        {
                            Id = 85,
                            Country = "Serbia",
                            Name = "Ivanjica",
                            PostalCode = "32310"
                        },
                        new
                        {
                            Id = 86,
                            Country = "Serbia",
                            Name = "Tutin",
                            PostalCode = "36320"
                        },
                        new
                        {
                            Id = 87,
                            Country = "Serbia",
                            Name = "Ljubovija",
                            PostalCode = "15320"
                        },
                        new
                        {
                            Id = 88,
                            Country = "Serbia",
                            Name = "Mali Zvornik",
                            PostalCode = "15318"
                        },
                        new
                        {
                            Id = 89,
                            Country = "Serbia",
                            Name = "Crna Trava",
                            PostalCode = "17527"
                        },
                        new
                        {
                            Id = 90,
                            Country = "Serbia",
                            Name = "Gadžin Han",
                            PostalCode = "18205"
                        },
                        new
                        {
                            Id = 91,
                            Country = "Serbia",
                            Name = "Bosilegrad",
                            PostalCode = "17540"
                        },
                        new
                        {
                            Id = 92,
                            Country = "Serbia",
                            Name = "Merošina",
                            PostalCode = "18233"
                        },
                        new
                        {
                            Id = 93,
                            Country = "Serbia",
                            Name = "Žabari",
                            PostalCode = "12260"
                        },
                        new
                        {
                            Id = 94,
                            Country = "Serbia",
                            Name = "Ražanj",
                            PostalCode = "18230"
                        },
                        new
                        {
                            Id = 95,
                            Country = "Serbia",
                            Name = "Malo Crniće",
                            PostalCode = "12306"
                        },
                        new
                        {
                            Id = 96,
                            Country = "Serbia",
                            Name = "Ljig",
                            PostalCode = "14240"
                        },
                        new
                        {
                            Id = 97,
                            Country = "Serbia",
                            Name = "Medveđa",
                            PostalCode = "17516"
                        },
                        new
                        {
                            Id = 98,
                            Country = "Serbia",
                            Name = "Osečina",
                            PostalCode = "14253"
                        },
                        new
                        {
                            Id = 99,
                            Country = "Serbia",
                            Name = "Preševo",
                            PostalCode = "17523"
                        },
                        new
                        {
                            Id = 100,
                            Country = "Serbia",
                            Name = "Bujanovac",
                            PostalCode = "17520"
                        });
                });

            modelBuilder.Entity("Klinika.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AddressId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JMBG")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Persons", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Klinika.Models.Guardian", b =>
                {
                    b.HasBaseType("Klinika.Models.Person");

                    b.ToTable("Guardians", (string)null);
                });

            modelBuilder.Entity("Klinika.Models.Patient", b =>
                {
                    b.HasBaseType("Klinika.Models.Person");

                    b.Property<string>("BloodType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GuardianId")
                        .HasColumnType("int");

                    b.HasIndex("GuardianId");

                    b.ToTable("Patients", (string)null);
                });

            modelBuilder.Entity("Klinika.Models.Worker", b =>
                {
                    b.HasBaseType("Klinika.Models.Person");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Workers", (string)null);
                });

            modelBuilder.Entity("Klinika.Models.Administrator", b =>
                {
                    b.HasBaseType("Klinika.Models.Worker");

                    b.Property<string>("SeniorityLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Administrators", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddressId = 1,
                            CreatedAt = new DateTime(2025, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@clinic.com",
                            FirstName = "Admin",
                            Gender = "M",
                            JMBG = "0000000000000",
                            LastName = "Adminovic",
                            PhoneNumber = "000-000-0000",
                            IsActive = true,
                            PasswordHash = "$2a$11$9P.it7ACUqHO8E4jPTtWPeg2smro6UFF7CFueUL5TLokpHqEmFBRe",
                            SeniorityLevel = "Senior"
                        });
                });

            modelBuilder.Entity("Klinika.Models.Doctor", b =>
                {
                    b.HasBaseType("Klinika.Models.Worker");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Doctors", (string)null);
                });

            modelBuilder.Entity("Klinika.Models.Secretary", b =>
                {
                    b.HasBaseType("Klinika.Models.Worker");

                    b.Property<string>("Qualification")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Secretaries", (string)null);
                });

            modelBuilder.Entity("Klinika.Models.Address", b =>
                {
                    b.HasOne("Klinika.Models.City", "City")
                        .WithMany("Addresses")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("Klinika.Models.AppointmentSlot", b =>
                {
                    b.HasOne("Klinika.Models.Doctor", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("Klinika.Models.Person", b =>
                {
                    b.HasOne("Klinika.Models.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Address");
                });

            modelBuilder.Entity("Klinika.Models.Guardian", b =>
                {
                    b.HasOne("Klinika.Models.Person", null)
                        .WithOne()
                        .HasForeignKey("Klinika.Models.Guardian", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Klinika.Models.Patient", b =>
                {
                    b.HasOne("Klinika.Models.Guardian", "Guardian")
                        .WithMany("Children")
                        .HasForeignKey("GuardianId");

                    b.HasOne("Klinika.Models.Person", null)
                        .WithOne()
                        .HasForeignKey("Klinika.Models.Patient", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guardian");
                });

            modelBuilder.Entity("Klinika.Models.Worker", b =>
                {
                    b.HasOne("Klinika.Models.Person", null)
                        .WithOne()
                        .HasForeignKey("Klinika.Models.Worker", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Klinika.Models.Administrator", b =>
                {
                    b.HasOne("Klinika.Models.Worker", null)
                        .WithOne()
                        .HasForeignKey("Klinika.Models.Administrator", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Klinika.Models.Doctor", b =>
                {
                    b.HasOne("Klinika.Models.Worker", null)
                        .WithOne()
                        .HasForeignKey("Klinika.Models.Doctor", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Klinika.Models.Secretary", b =>
                {
                    b.HasOne("Klinika.Models.Worker", null)
                        .WithOne()
                        .HasForeignKey("Klinika.Models.Secretary", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Klinika.Models.City", b =>
                {
                    b.Navigation("Addresses");
                });

            modelBuilder.Entity("Klinika.Models.Guardian", b =>
                {
                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
